[project]
name = "frik"
version = "1.0.0"
description = "A Wayland-exclusive screenshot tool that extracts text from your screenshot"
readme = "README.md"
authors = [
    { name = "quandelaa", email = "sergiotobamasilalahi@gmail.com" }
]
keywords = ["screenshot", "wayland", "cli"]
requires-python = ">=3.12"
dependencies = [
    "pyperclip>=1.11.0",
    "pytesseract>=0.3.13",
]

[project.scripts]
frik = "frik.main:main"

[project.urls]
Repository = "https://github.com/quandelaa/frik"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
